#This plugin is made by D-Pear
#You can visit my Minecraft server 'meown.top'(JE) or 'be.meown.top'(BE)
#This plugin is still in developing, if not necessary please don't use this in produced environment
#YOU CAN REPORT BUGS IN THE GITHUB
#https://github.com/MeownMC/GeyserPermGroup
#Thank for use this plugin

ConfigVersion: 2.2
SCID-C: #在此处输入密钥
OldMinecraftVersion: false
EnabledFunction:
  CommandAlert: true
  BedrockMenu: true
  ElitemobsHandler: true
  VersionCommand: true
  IP2Region: false    #需自行下载数据库
Register:
  EventListener: true
  Bungeecord: true
VersionCheck:
  FloodGate: true
  ViaVersion: false
Version:
  Bedrock:
    Enable: true
    AutoLogin:
      Command: false
      AuthMe: true
      AuthMe_CommandRegister: true
    AutoPermissionGroup:
      Vault: true
      Group: 'bedefault'
    Command:
      OnPlayerJoin:
        - 'Console~authme register %PlayerName %Password'
      OnPlayerRegister:
        - 'Console~lp user %PlayerUUID parent set bedefault'
        - 'Console~authme password %PlayerName %Password'
    Message:
      OnPlayerJoin:
        - '§8[§4§l系统§8] §6§l检测到基岩版玩家，已自动为您自动登入'
        - '§7 '
        - '§8[§4§l系统§8] §7目前喵喵领域服务器的基岩版支持还处于测试阶段'
        - '§8[§4§l系统§8] §7如果出现问题可以向服务器团队反馈哦~'
        - '§7 '
      OnPlayerRegister:
        - '§8[§4§l系统§8] §e§l亲爱的基岩版玩家，已为您自动注册并切换权限'
  Other:
    Enable: true
    AutoLogin:
      Command: false
      AuthMe: false
      AuthMe_CommandRegister: false
    Command:
      OnPlayerJoin: []
      OnPlayerRegister: []
    Message:
      OnPlayerJoin:
        - '§8[§4§l系统§8] §6§l欢迎来到喵喵领域服务器'
      OnPlayerRegister: []
  FastLogin:
    Enable: true
    AutoLogin:
      AuthMe: true
    Command: []
    Message:
      - '§8[§4§l系统§8] §6§l检测到您正在使用外置登录，已自动为您登录至喵喵领域服务器'
      - '§7 '
      - '§8[§4§l系统§8] §7目前喵喵领域服务器的外置登录还不完善'
      - '§8[§4§l系统§8] §7如果出现问题可以向服务器团队反馈哦~'
      - '§7 '
Command:
  #Command here will execute as console after a player join
  OnPlayerJoin: 'checkplayerbe %PlayerName'
  Login: 'login %Password'
  Register: 'register %Password %Password'
Actions:
  AutoKick:
    Enable: true
    KickMessage: '§8[§4§l系统§8] §c你不是基岩版玩家'
#This part is still in develop
Menus:
  example:
    type: 'ModalForm'
    title: 'EXAMPLE'
    content: '你好啊，欢迎来到我们服务器'
    button1: '打开主菜单'
    button2: '打开功能菜单'
    action:
      button1: 'cd'
      button2: 'gn'
  example_s:
    type: 'SimpleForm'
    title: 'EXAMPLE'
    content: '你好啊，选择一个'
    button:
      - '主城'
      - '地狱'
      - '末地'
    image:
      - 'Null'
      - 'Null'
      - 'Null'
    action:
      - 'warp spawn'
      - 'warp dy'
      - 'warp md'
  example_c:
    type: 'CustomForm'
    title: 'CustomFormExample'
    Form:
      - 'a'
      - 'c'
      - 'b'
      - 'c'
      - 'd'
      - 'c'
      - 'e'
      - 'c'
      - 'f'
    Components:
      a:
        type: 'Dropdown'
        text: '我是一个Dropdown'
        options:
          - '没错'
          - '可能吧'
          - '不对'
      b:
        type: 'Input'
        text: '输入点东西'
        content: '->'
      c:
        type: 'Label'
        text: '-----分割-----'
      d:
        type: 'Slider'
        title: '数值'
        left: 0
        right: 25
        step: 1
        default: 16
      e:
        type: 'StepSlide'
        text: '你最喜欢的语言?'
        steps:
          - 'C'
          - 'C++'
          - 'java'
          - 'C#'
          - 'python'
        default: 2
      f:
        type: 'Toggle'
        title: 'Click Me'
        default: true
    Target:
      - 'Msg~你认为第一个控件{Placeholder:C~0}({Placeholder:0})是一个Dropdown'
      - 'Msg~你在第二个地方输入了: {Placeholder:2}'
      - 'Msg~你的数值是: {Placeholder:4}'
      - 'Msg~你最喜欢的语言是: {Placeholder:C~6}({Placeholder:6})'
      - 'Msg~按钮的选项是: {Placeholder:8}'
  tpa:
    type: 'PlayerListForm'
    title: '玩家互传'
    content: '今天要传送到谁那里呢？'
    icon: true
    removeself: true
    text: '%PlayerName'
    action: 'tpa %PlayerName'
    button: '取消'
    buttonaction: 'Null'
  EliteMobs:
    type: 'EliteMobsBossesForm'
    title: '精英怪列表'
    content: '今天要追踪哪个精英怪呢?'
    button: '取消'
    buttonaction: 'Null'
CommandAlert:
  CommandList:
    tssbb:
      Replace: false
      Arg: 0
      Permission: Null
      Target:
        - 'gm 0'
        - 'say 我是生存模式'
      Tab: []
    nssbb:
      exFunction:
        PlayerVersion: false
        PermissionGroup: false
        PlayerWorld: false
        ArgAmount: false
        Arg: false
      Replace: false
      Arg: 0
      Permission: Null
      Target:
        - 'gm 1'
        - 'say 我是创造模式'
    wssbb:
      Replace: true
      Arg: 1
      Permission: Null
      Expression: Null
      Target:
        - 'gm {0}'
        - 'say 我是{0}模式'
      Target-no-permission: []
      Target-fail-expression: []
  Hard:
    - 'tssbb'
    - 'nssbb'
  Soft:
    - 'wssbb'
SimulationDistance:
  world: 3
  plotworld: 3
ViewDistance:
  world: 5
  plotworld: 4
RealisticSeasonsPAPIFix:
  EnabledWorld:
    - 'world'
EliteMobs:
  CustomBossesList:
    - 'FirstBossName'
    - 'SecondBossName'