#This plugin is made by D-Pear[QQ:1448360624]
#You can visit my Minecraft server 'mc.meown.top'(JE) or 'be.meown.top'(BE)
#This plugin is still in developing, if not necessary please don't use this in produced environment
#YOU CAN REPORT BUGS IN THE GITHUB
#https://github.com/D-Pear/GeyserPermGroup
#Thank for use this plugin

ConfigVersion: 2.1
SCID-C:
Register:
  #Warning!Still in develop!DO NOT set to true!
  EventListener: false
VersionCheck:
  FloodGate: true
  ProtocolSupport: true
  ViaVersion: false
Version:
  Bedrock:
    Enable: true
    AutoLogin:
      Command: false
      AuthMe: true
    AutoPermissionGroup:
      Vault: true
      Group: 'bedefault'
    Command:
      OnPlayerJoin:
        - 'authme register %PlayerName %Password'
      OnPlayerRegister:
        - 'lp user %PlayerUUID parent set bedefault'
        - 'authme password %PlayerName %Password'
    Message:
      OnPlayerJoin:
        - '§8[§4§l系统§8] §6§l检测到基岩版玩家，已自动为您自动登入'
        - '§7 '
        - '§8[§4§l系统§8] §7目前喵喵领域服务器的基岩版支持还处于测试阶段'
        - '§8[§4§l系统§8] §7如果出现问题可以向服务器团队反馈哦~'
        - '§7 '
      OnPlayerRegister:
        - '§8[§4§l系统§8] §e§l亲爱的基岩版玩家，已为您自动注册并切换权限'
  Other:
    Enable: true
    AutoLogin:
      Command: false
      AuthMe: false
    Command:
      OnPlayerJoin: []
      OnPlayerRegister: []
    Message:
      OnPlayerJoin:
        - '§8[§4§l系统§8] §6§l欢迎来到喵喵领域服务器'
      OnPlayerRegister: []
Command:
  #Command here will execute as console 1500ms after a player join
  OnPlayerJoin_Delay: 'Null'
  Login: 'login %Password'
Actions:
  AutoKick:
    Enable: true
    KickMessage: '§8[§4§l系统§8] §c你不是基岩版玩家'
#This part is still in develop
Menus:
  example:
    type: 'ModalForm'
    title: 'EXAMPLE'
    content: '你好啊，欢迎来到我们服务器'
    button1: '打开主菜单'
    button2: '打开功能菜单'
    action:
      button1: 'cd'
      button2: 'gn'
  example_s:
    type: 'SimpleForm'
    title: 'EXAMPLE'
    content: '你好啊，选择一个'
    button:
      - '主城'
      - '地狱'
      - '末地'
    image:
      - 'Null'
      - 'Null'
      - 'Null'
    action:
      - 'warp spawn'
      - 'warp dy'
      - 'warp md'
  tpa:
    type: 'PlayerListForm'
    title: '玩家互传'
    content: '今天要传送到谁那里呢？'
    text: '%PlayerName'
    removeself: true
    action: 'tpa %PlayerName'
    button: '取消'
    buttonaction: 'Null'
CommandAlert:
  RegisterList:
    - 'tssbb'
    - 'nssbb'
    - 'wssbb'
  Hard:
    tssbb:
      Replace: false
      Arg: 0
      Permission: Null
      Goal:
        - 'gm 0'
        - 'say 我是生存模式'
    nssbb:
      exFunction:
        PlayerVersion: false
        PermissionGroup: false
        ArgAmount: false
        Arg: false
      Replace: false
      Arg: 0
      Permission: Null
      Goal:
        - 'gm 1'
        - 'say 我是创造模式'
    wssbb:
      Replace: true
      Arg: 1
      Permission: Null
      Goal:
        - 'gm {0}'
        - 'say 我是{0}模式'
  Soft:
    Source:
      - 'tsb'
      - 'nsb'
      - 'wsb'
    Goal:
      - 'gm 0'
      - 'gm 1'
      - 'gm 3'