name: GeyserPermGroup
main: dpear.gpg.main
version: 2.2
api-version: 1.17
author: Dameng23333
website: meown.top
depend:
  - floodgate
  - PlaceholderAPI
softdepend:
  - AuthMe
  - PlugManX
  - ViaVersion
  - Vault
  - EliteMobs
commands:
  bemenu:
    usage: "Use /bemenu help to show usages."
    description: "Open a be form"
    permission: "dpear.gpg"
    permission-message: "输你妈输"