name: GeyserPermGroup
main: dpear.gpg.main
version: 2.1
api-version: 1.12
author: D-Pear
website: meown.top
depend:
  - floodgate
  - PlaceholderAPI
softdepend:
  - AuthMe
  - PlugManX
  - ViaVersion
  - Vault
  - EliteMobs
commands:
  checkplayerbe:
    usage: "/checkplayerbe <player-name>"
    description: "Auto change the permission group if the player is using BE"
    permission: ""
    permission-message: "You cannot do that!"
  regbeplayer:
    usage: "/regbeplayer <be-player-name>"
    description: "Auto register if BE player"
    permission: ""
    permission-message: "You cannot do that!"
  bemenu:
    usage: "Use /bemenu help tp show usages."
    description: "Open a be form"
    permission: "dpear.gpg"
    permission-message: "You have no permission"