name: GeyserPermGroup
main: dpear.gpg.main
version: 2.2
api-version: 1.17
author: D-Pear
website: meown.top
depend:
  - floodgate
  - PlaceholderAPI
softdepend:
  - AuthMe
  - PlugManX
  - ViaVersion
  - Vault
  - EliteMobs
  - MineDownPlugin
commands:
  checkplayerbe:
    usage: "/checkplayerbe <player-name>"
    description: ""
    permission: ""
    permission-message: "You cannot do that!"
  regbeplayer:
    usage: "/regbeplayer <be-player-name>"
    description: ""
    permission: ""
    permission-message: "You cannot do that!"
  bemenu:
    usage: "Use /bemenu help to show usages."
    description: "Open a be form"
    permission: ""
    permission-message: "You have no permission"