# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Auto-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml --errors
      
    - uses: actions/cache@v2
      if: github.event_name != 'pull_request'
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - uses: actions/upload-artifact@v2
      if: github.event_name != 'pull_request'
      with:
        name: GeyserPermGroup.jar
        path: staging
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      if: github.event_name != 'pull_request'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "exp"
        prerelease: true
        title: "GeyserPermGroup Auto Build Version"
        files: |
          target/GeyserPermGroup-*.jar
